# Generated by Django 2.2.dev20181205203023 on 2018-12-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=10000)),
                ('link', models.URLField()),
                ('number_of_upvotes', models.IntegerField()),
            ],
        ),
    ]
