# Generated by Django 2.2.dev20181205203023 on 2018-12-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article_id', models.IntegerField()),
                ('source_id', models.IntegerField()),
                ('title', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=10000)),
                ('link', models.URLField()),
                ('number_of_upvotes', models.IntegerField()),
                ('agreement_index', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('article_match', models.IntegerField()),
                ('similarity_percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('reliability_index', models.FloatField()),
                ('number_of_posts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('question', models.CharField(max_length=1000)),
                ('answer_one', models.CharField(max_length=100)),
                ('answer_two', models.CharField(max_length=100)),
                ('answer_three', models.CharField(max_length=100)),
                ('answer_correct', models.CharField(max_length=100)),
            ],
        ),
    ]
