# Generated by Django 2.2.dev20181205203023 on 2018-12-07 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reliability_index', models.IntegerField()),
                ('number_of_posts', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='articles',
            name='id',
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.CharField(max_length=1000)),
                ('article_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.Articles')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_match', models.CharField(max_length=1000)),
                ('similarity_percentage', models.IntegerField()),
                ('article_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.Articles')),
            ],
        ),
    ]
