# Generated by Django 2.2.dev20181205203023 on 2018-12-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20181207_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesimilarity',
            name='article_title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='article_title',
            field=models.CharField(max_length=150),
        ),
    ]
