# Generated by Django 2.2.dev20181205203023 on 2018-12-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20181210_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='agreement_index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
